### ISSUE TITLE
8005 in bind

### ISSUE THREAD

**Issue by linmaosong** [YingXingGuiHai/PolarisTomcatServer#1]
how can i change the SHUTDOWN port 8005 ,thanks！

**Comment by wangjian1106** [comment]
Hi, it is a reasonable feature but not yet supported, I will finish this today, but the IntelliJ plugin reviewing may take two working days.  
### workaround
1. You may check  "Store as project file" in the config panel.
Remember where the config file saved.
<img width="592" alt="image" src="https://github.com/YingXingGuiHai/PolarisTomcatServer/assets/8831636/6c72c253-6700-4d8c-a821-d74714f35e0a">   

2. Then open and edit the config file manually
Search `jmxRemotePassword` to find the text like this:
```xml
    <option name="jmxRemoteAccess" value="bvbtduete" />
    <option name="jmxRemotePassword" value="HDfSmW3Ykd5E1jUnj7" />
    <option name="openBrowser" value="true" />
    <option name="tomcatServer">
```
Add `<option name="adminPort" value="your-port" />` in a new line after `<option name="jmxRemotePassword" value="HDfSmW3Ykd5E1jUnj7" />` **(the jmxRemotePassword's value may different in your file)**   
   
Just like this:
```xml
    <option name="jmxRemoteAccess" value="bvbtduete" />
    <option name="jmxRemotePassword" value="HDfSmW3Ykd5E1jUnj7" />
    <option name="adminPort" value="8006" /> <!-- add this line to change admin port from 8005 to 8006 -->
    <option name="openBrowser" value="true" />
    <option name="tomcatServer">
```

```diff
- Please note that this modification will be lost after saving in config panel.
```

**Comment by wangjian1106** [comment]
@linmaosong The new version `1.0.6` is available now.

**Comment by linmaosong** [comment]
> @linmaosong The new version `1.0.6` is available now.
That's great!

**Comment by linmaosong** [comment]
Another issue is that the console logs display garbled Chinese characters！It has been set up as shown in the picture！
![Uploading 1710902147(1).jpg…]()

**Comment by linmaosong** [comment]
Another issue is that the console logs display garbled Chinese characters！It has been set up as shown in the picture！
![1710902147(1)](https://github.com/YingXingGuiHai/PolarisTomcatServer/assets/27754773/c4d2adab-af9d-4666-892f-d2cd74e1d31d)

**Comment by wangjian1106** [comment]
Are you using a Windows OS?  On Windows platform, the default Chinese encoding is `GB2312`, run `[System.Text.Encoding]::Default` in powershell to check this out.   
### Solution
1. Open IntelliJ IDEA, click `Menu -> Edit Custom VM Options` in menu bar.
2. Add encoding settings to the opened file.
```
-Dfile.encoding=UTF-8
```
3. Save and restart IntelliJ IDEA.
    
Now you can remove the setting of `-Dfile.encoding=UTF-8` from tomcat server settings for good.

**Comment by linmaosong** [comment]
Niubi

**Comment by linmaosong** [comment]
My problems have all been solved！

**Comment by wangjian1106** [comment]
> My problems have all been solved！

Glad to hear that.

**Comment by wangjian1106** [comment]
> Niubi

Hahaha, I am Chinese too.
