### ISSUE TITLE
丢失文件

### ISSUE THREAD

**Issue by linmaosong** [YingXingGuiHai/PolarisTomcatServer#2]
hi 大神，
一、tomcat 启动  对于 多模块的 maven 项目，打包后 关联模块jar包 丢失。
二、更改某些配置文件，没有生效，还是因为没有把最新的配置文件去打包更新。

以上俩个问题 都是我手动 执行maven package 才好的

**Comment by wangjian1106** [comment]
你好，

我自己的测试项目也有多个模块，似乎没有你说的问题，可以提供一份能复现问题的样例项目吗？  
如果确实有问题，可以配置一下使用 maven 命令打包项目，**取消**勾选下图中的复选框。
<img width="595" alt="image" src="https://github.com/YingXingGuiHai/PolarisTomcatServer/assets/8831636/b8da6bec-666e-4bed-8cd1-0548c2f6a447">

**Comment by linmaosong** [comment]
这个去掉勾选，好使了，感谢！

**Comment by wangjian1106** [comment]
好的，可以麻烦构造并提供一份能复现问题的简单样例项目吗？谢谢。

**Comment by linmaosong** [comment]
这个真不好意思！

**Comment by wangjian1106** [comment]
好的，没关系。
