### ISSUE TITLE
not able to set the url in tomcat

### ISSUE THREAD

**Issue by Satyen071** [YingXingGuiHai/PolarisTomcatServer#3]
Not able to set the url 

![image](https://github.com/YingXingGuiHai/PolarisTomcatServer/assets/36238546/0b6b046f-513f-4b52-99aa-a18daded8d0a)

can you help here

**Comment by wangjian1106** [comment]
Oh, i see. I will fix it ASAP.

**Comment by Satyen071** [comment]
Thank you

**Comment by Satyen071** [comment]
Is it fixed @wangjian1106 ?

**Comment by wangjian1106** [comment]
Yes, I have fix it.  
But JetBrains will take one or two days to review the new version. Please wait. I will notify you here once the new version is ready.

**Comment by Satyen071** [comment]
okay thank you

**Comment by wangjian1106** [comment]
Hi @Satyen071 , the new version now is available.

**Comment by Satyen071** [comment]
Thank you @wangjian1106 i will check and let you know if it's working

**Comment by wangjian1106** [comment]
Hi @Satyen071 , Does it worked? If you has no more questions, could you please change the stars to 5 at the plugin reviews' page? This is very important to me. Thank you.
